-- TOTAL QUANTITY
select SUM(QUANTITY) as TOTAL_QUANTITY
FROM ATMOSYNC_PROJ_2_DB.RAW.CONTAINER_DETAILS;

-- SOURCE WISE QUANTITY
SELECT 
    SOURCE,
    SUM(QUANTITY) as TOTAL_QUANTITY
FROM ATMOSYNC_PROJ_2_DB.RAW.CONTAINER_DETAILS
GROUP BY SOURCE
ORDER BY TOTAL_QUANTITY DESC;

-- SOURCE WISE QUANTITY
SELECT 
    SOURCE,
    SUM(QUANTITY) as TOTAL_QUANTITY
FROM ATMOSYNC_PROJ_2_DB.RAW.CONTAINER_DETAILS
GROUP BY SOURCE
ORDER BY TOTAL_QUANTITY DESC;

-- DESTINATION WISE QUANTITY
SELECT 
    DESTINATION,
    SUM(QUANTITY) as TOTAL_QUANTITY
FROM ATMOSYNC_PROJ_2_DB.RAW.CONTAINER_DETAILS
GROUP BY DESTINATION
ORDER BY TOTAL_QUANTITY DESC;

