SELECT * 
from ATMOSYNC_Proj_2_DB.RAW.IOT_SENSOR_DATA;


-- TOTAL ROWS
SELECT COUNT(*) as TOTAL_ROWS
FROM ATMOSYNC_Proj_2_DB.RAW.IOT_SENSOR_DATA;


-- IoT Sensor Avg Temp
SELECT AVG(temperature) as AVG_TEMPERATURE
FROM ATMOSYNC_Proj_2_DB.RAW.IOT_SENSOR_DATA;

-- MAX & MIN TEMP
SELECT
    MAX(temperature) as MAX_TEMPERATURE,
    MIN(temperature) as MIN_TEMPERAYURE
FROM ATMOSYNC_PROJ_2_DB.RAW.IOT_SENSOR_DATA;

-- AVG HUMIDITY
SELECT AVG(vibration) as AVG_VIBRATION
FROM ATMOSYNC_Proj_2_DB.RAW.IOT_SENSOR_DATA;

-- CITY WISE SENSOR DATA
SELECT
    location,
    count(*) as SENSOR_READINGS
FROM ATMOSYNC_PROJ_2_DB.RAW.IOT_SENSOR_DATA
GROUP BY location
ORDER BY SENSOR_READINGS DESC;

