                                     -- SHIPHMENT, MARKET & ALERT ANALYSIS


-- MOST FREQUENTLY USED SOURCE
SELECT
    SOURCE,
    COUNT(*) AS SHIPMENT_COUNT
FROM ATMOSYNC_PROJ_2_DB.RAW.CONTAINER_DETAILS
GROUP BY SOURCE
ORDER BY SHIPMENT_COUNT DESC;

-- MOST FREQUENTLY USED DESTINATION
SELECT
    DESTINATION,
    COUNT(*) AS SHIPMENT_COUNT
FROM ATMOSYNC_PROJ_2_DB.RAW.CONTAINER_DETAILS
GROUP BY DESTINATION
ORDER BY SHIPMENT_COUNT DESC;

-- TOTAL QUANTITY BY ROUTE
SELECT
    SOURCE,
    DESTINATION,
    SUM(QUANTITY) AS TOTAL_QUANTITY
FROM ATMOSYNC_PROJ_2_DB.RAW.CONTAINER_DETAILS
GROUP BY SOURCE, DESTINATION
ORDER BY TOTAL_QUANTITY DESC;

-- AVG COMMODITY PRICE BY MARKET 
SELECT
    MARKET,
    ROUND(AVG(PRICE),2) AS AVG_PRICE
FROM ATMOSYNC_PROJ_2_DB.RAW.COMMODITY_PRICE
GROUP BY MARKET
ORDER BY AVG_PRICE DESC;

-- HIGHEST PRICED COMMODITY
SELECT
    COMMODITY,
    MAX(PRICE) AS HIGHEST_PRICE
FROM ATMOSYNC_PROJ_2_DB.RAW.COMMODITY_PRICE
GROUP BY COMMODITY
ORDER BY HIGHEST_PRICE DESC;

-- LOWEST PRICED COMMODITY
SELECT
    COMMODITY,
    MIN(PRICE) AS LOWEST_PRICE
FROM ATMOSYNC_PROJ_2_DB.RAW.COMMODITY_PRICE
GROUP BY COMMODITY
ORDER BY LOWEST_PRICE ;

-- PRODUCT + SHIPHMENT + SENSOR COMBINED ANALYSIS
SELECT
    I.PRODUCT_ID,
    COUNT(DISTINCT I.CONTAINER_ID) AS TOTAL_CONTAINERS,
    ROUND(AVG(I.TEMPERATURE),2) AS AVG_TEMP,
    ROUND(AVG(I.HUMIDITY),2) AS AVG_HUMIDITY,
    ROUND(AVG(I.VIBRATION),2) AS AVG_VIBRATION,
    SUM(C.QUANTITY) AS TOTAL_QUANTITY
FROM ATMOSYNC_PROJ_2_DB.RAW.IOT_SENSOR_DATA I
JOIN ATMOSYNC_PROJ_2_DB.RAW.CONTAINER_DETAILS C 
    ON I.CONTAINER_ID = C.CONTAINER_ID
GROUP BY I.PRODUCT_ID
ORDER BY TOTAL_QUANTITY DESC;

-- ROUTE + TEMP ANALYSIS
SELECT
    C.SOURCE,
    C.DESTINATION,
    COUNT(DISTINCT C.CONTAINER_ID) AS TOTAL_CONTAINERS,
    ROUND(AVG(I.TEMPERATURE),2) AS AVG_TEMP,
    ROUND(MAX(I.TEMPERATURE),2) AS MAX_TEMP,
FROM ATMOSYNC_PROJ_2_DB.RAW.CONTAINER_DETAILS C
JOIN ATMOSYNC_PROJ_2_DB.RAW.IOT_SENSOR_DATA I 
    ON C.CONTAINER_ID = I.CONTAINER_ID
GROUP BY C.SOURCE, C.DESTINATION
ORDER BY AVG_TEMP DESC;

-- SENSOR ALERT classification
SELECT
    CONTAINER_ID,
    TEMPERATURE,
    HUMIDITY,
    VIBRATION,
    CASE
        WHEN TEMPERATURE > 30 OR HUMIDITY > 80 OR VIBRATION > 0.5 
        THEN 'ALERT'
        ELSE 'NORMAL'
    END AS SENSOR_STATUS
FROM ATMOSYNC_PROJ_2_DB.RAW.IOT_SENSOR_DATA;

-- COUNT OF NORMAL VS ALERT RECORDS
SELECT
    CASE
        WHEN TEMPERATURE > 30 OR HUMIDITY > 80 OR VIBRATION > 0.5 
        THEN 'ALERT'
        ELSE 'NORMAL'
    END AS SENSOR_STATUS,
    COUNT(*) AS  RECORD_COUNT
FROM ATMOSYNC_PROJ_2_DB.RAW.IOT_SENSOR_DATA
GROUP BY SENSOR_STATUS;
        
        