-- COMMODITY WISE AVG PRICE
SELECT
    commodity,
    ROUND(AVG(price),2) as AVG_PRICE
FROM ATMOSYNC_PROJ_2_DB.RAW.COMMODITY_PRICE
GROUP BY commodity
ORDER BY AVG_PRICE;

-- MARKET WISE AVG PRICE
SELECT
    market,
   ROUND(AVG(price),2) as AVG_PRICE
FROM ATMOSYNC_PROJ_2_DB.RAW.COMMODITY_PRICE
GROUP BY market
ORDER BY AVG_PRICE;

-- TOP 10 HIGHEST PRICE COMMODITY PRICE
SELECT *
FROM ATMOSYNC_PROJ_2_DB.RAW.COMMODITY_PRICE
ORDER BY price
LIMIT 10;