                                        -- SENSOR & PRODUCT ANALYSIS


-- Container wise highest Temperature
SELECT 
    container_id,
    MAX(temperature) as MAX_TEMPERATURE
FROM ATMOSYNC_PROJ_2_DB.RAW.IOT_SENSOR_DATA
GROUP BY container_id
ORDER BY MAX_TEMPERATURE;

-- Container wise highest Vibration
SELECT
    CONTAINER_ID,
    MAX(VIBRATION) AS MAX_VIBRATION
FROM ATMOSYNC_PROJ_2_DB.RAW.IOT_SENSOR_DATA
GROUP BY CONTAINER_ID
ORDER BY MAX_VIBRATION;

-- HIGH HUMIDITY CONTAINERS
SELECT
    CONTAINER_ID,
    AVG(HUMIDITY) AS AVG_HUMIDITY
FROM ATMOSYNC_PROJ_2_DB.RAW.IOT_SENSOR_DATA
GROUP BY CONTAINER_ID
HAVING AVG_HUMIDITY > 70
ORDER BY AVG_HUMIDITY DESC;


-- PRODUCT WISE AVG TEMP
SELECT
    PRODUCT_ID,
    AVG(TEMPERATURE) AS AVG_TEMPERATURE
FROM ATMOSYNC_PROJ_2_DB.RAW.IOT_SENSOR_DATA
GROUP BY PRODUCT_ID
ORDER BY AVG_TEMPERATURE DESC;

-- PRODUCT WISE SENSOR CONDITIONS
SELECT 
    PRODUCT_ID,
    ROUND(AVG(TEMPERATURE),2) AS AVG_TEMPERATURE,
    ROUND(AVG(HUMIDITY),2) AS AVG_HUMIDITY,
    ROUND(AVG(VIBRATION),2) AS AVG_VIBRATION
FROM ATMOSYNC_PROJ_2_DB.RAW.IOT_SENSOR_DATA
GROUP BY PRODUCT_ID
ORDER BY PRODUCT_ID;
