-- CITY WISE MARKETS 
SELECT
    city,
    COUNT(*) as MARKET_COUNT
FROM ATMOSYNC_PROJ_2_DB.RAW.MARKET_DETAILS
GROUP BY city
ORDER BY MARKET_COUNT DESC;

-- STATE WISE MARKET
SELECT
    state,
    COUNT(*) as MARKET_COUNT
FROM ATMOSYNC_PROJ_2_DB.RAW.MARKET_DETAILS
GROUP BY state
ORDER BY MARKET_COUNT DESC;

