table container_details
	lineageTag: 7714ebbf-90c2-423a-836f-1d77e7dd9662

	measure 'Total Containers' = DISTINCT(container_details[container_id])
		lineageTag: 537f9573-5b90-4d06-8c58-a9c1841a4c46

	measure 'Total shipments' = COUNTROWS(container_details)
		formatString: 0
		lineageTag: 29dc71f3-1c5c-4a75-89d4-c037deb2007e

	measure 'Total Quantity' = SUM(container_details[quantity])
		formatString: 0
		lineageTag: 85e519c6-fb45-45a1-960e-2617084c217b

	column container_id
		dataType: string
		lineageTag: 1eae6a2c-897d-44c7-88a4-2c7217ffb638
		summarizeBy: none
		sourceColumn: container_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 8a37f1c1-62fc-4806-9bbd-0fff20e599ee
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: bfe7a62c-71e1-4597-8c88-2f1391fc02ce
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		lineageTag: b72422fa-fb50-471e-97b2-cc80ce0fa6c2
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column destination
		dataType: string
		lineageTag: 12084e74-2f22-4967-8fb2-d9c957df4336
		summarizeBy: none
		sourceColumn: destination

		annotation SummarizationSetBy = Automatic

	column dispatch_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e56a0423-cc42-401b-8e6b-21ab09170593
		summarizeBy: none
		sourceColumn: dispatch_date

		variation Variation
			isDefault
			relationship: 9d3537c7-e1ae-4c39-9d85-8c8ff8182db5
			defaultHierarchy: LocalDateTable_7d132e29-dcc4-4a1d-9dc9-26408af02860.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition container_details = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Dell\Desktop\Project 2 (Infotact Solutions)\Datasets\container_details.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"container_id", type text}, {"product_id", type text}, {"quantity", Int64.Type}, {"source", type text}, {"destination", type text}, {"dispatch_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

